'use client';

// import type { Metadata } from 'next'
import Image from 'next/image'
import { Roboto } from 'next/font/google'
import { Box, Button, Grommet, Header, Page as GPage, PageContent } from 'grommet'
import { Add, Search } from 'grommet-icons'
import LayoutProps from './layout.props'
import theme from './theme'
import Link from 'next/link';
import { usePathname } from 'next/navigation';

const roboto = Roboto({
  weight: '400',
  subsets: ['latin'],
})

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

const Layout: React.FC<LayoutProps> = ({ children }) => {
  const pathname = usePathname()
console.log(pathname)
  return (
    <html lang="es">
        <body className={roboto.className}>
          <Grommet theme={theme} background="brand" full="min">
            <Box gap="large">

              <Header pad="medium" height="fit" align="start">
                <Box basis='300px' gap="xsmall">
                  {/* MENU  */}
                  <Link href="/buscador">
                    <Button active={pathname === '/buscador'} icon={<Search size="small" />} label="buscar reseñas" />
                  </Link>
                  <Link href="/enviar">
                    <Button active={pathname === '/enviar'} icon={<Add size="small" />} label="enviar una reseña" />
                  </Link>
                </Box>
                <Box align="center">
                  <a href="/">
                    <Image src="/logo.svg" width="350" height="50" alt="logo"/>
                  </a>
                </Box>
                <Box align="end" basis='300px'>
                  {/* ACCOUNT INFORMATION */}
                </Box>
              </Header>
              {children}
            </Box>
          </Grommet>
        </body>
      </html>
  )
}

export default Layout;