name: ESLint

on: [push]

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - run: npm install
      - run: |
          export ESLINT_DISABLE_ANY=true
          export ESLINT_DISABLE_RULE="import/newline-between-groups"
          npm run lint
