name: ESLint

on: [push]

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - run: npm install
      - run: |
          npx eslint --no-error-on-unmatched-pattern --max-warnings 0 \
          --rule "@typescript-eslint/no-empty-interface: off" \
          --rule "@typescript-eslint/no-explicit-any: off" \
          --rule "import/newline-between-groups: off" \
          --rule "import/order: off"
